### ISSUE TITLE
[Bug] Director metadata wrong on torrents

### ISSUE THREAD

**Issue by therealbungus** [HDInnovations/UNIT3D-Community-Edition#1824] opened 2021-07-01 20:11 UTC
**Describe the bug**
The director metadata is wrong on some torrents. It is pulling from a completely random page it seems like, as some torrents list the director as an actor who has also directed other movies, or is listing the director as someone who had nothing to do with the movie.

**To Reproduce**
1. Submit a torrent
2. Look at director metadata next to the IMDB and TMDB IDs

**Expected behavior**
Should show the correct director of the movie listed on the TMDB page

**Screenshots**
![chrome_2021-07-01_15-03-11](https://user-images.githubusercontent.com/449237/124183164-7abe6f80-da7d-11eb-9b0b-c0172539ee75.png)
![chrome_2021-07-01_15-10-56](https://user-images.githubusercontent.com/449237/124183978-8f4f3780-da7e-11eb-8077-a30e2c2cc204.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.3.0-4
- Laravel Version: 8.22.1
- PHP Version: Cannot find
- Database Driver & Version: Cannot find
- Web Server Driver & Version: Cannot find
- OS Driver and Version: Cannot find

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 91.0.4472.114

**Additional context**
Some torrents don't show a director for the movie at all, and some show it as a completely random/wrong person

**Comment by Alkl58** [comment] 2021-07-04 12:12
The issue is:
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/f21e874d13370791639f74cf3346c910977b1246/resources/views/torrent/partials/movie_meta.blade.php#L72

It should be:
```php
@php $director = $meta->crew->where('job' ,'=', 'Director')->sortBy('order')->first(); @endphp 
```

It would require a new DB entry, aswell additional TMDB Parsing.

I would do it, if I knew how to create DB entries.

**Comment by kREATUr67** [comment] 2022-07-31 18:55
will this error be fixed at some point?

**Comment by HDVinnie** [comment] 2022-08-03 13:32
Yes

**Comment by Roardom** [comment] 2023-02-10 14:37
With the latest PR merged, technically, this issue is fixed. There will simply just be no director for incorrect cases instead of having the wrong person displayed.

**Closed** 2023-02-10 16:01 UTC
Labels: Bug, PR Welcome!
