### ISSUE TITLE
[Feature] Bot telegram chat

### ISSUE THREAD

**Issue by alebupal** [HDInnovations/UNIT3D-Community-Edition#1401] opened 2020-07-09 11:56 UTC
Hello, I am on a tracker where in the chat they have a bot that communicates the messages of the telegram group and the chat. 
I've been researching and done with this https://github.com/Shahan/shoutboxMirrorBot.
It would be interesting to add a chat bot that has this functionality.
A greeting and thanks!

**Comment by HDVinnie** [comment] 2020-07-09 12:05
Duplicate of https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1391

**Closed by HDVinnie** 2020-07-09 12:05 UTC
Labels: Duplicate, Feature

**Comment by alebupal** [comment] 2020-07-09 12:11
Is not the same. I suggest a chat bot that integrates the messages from the chat and from a telegram group. Here #1391 a bot is requested to notify the uploads.

**Comment by HDVinnie** [comment] 2020-07-09 14:23
Yes but they both have to do with a Telegram bot. You can comment on the already open feature request issue that is related saying "it may also be nice to have two way communication with the site chat and telegram chat via the telegram bot". Something along those lines.
