### ISSUE TITLE
[Bug] Error 404 when no similiar torrents found

### ISSUE THREAD

**Issue by Neodkbits** [HDInnovations/UNIT3D-Community-Edition#3805] opened 2024-05-03 05:04 UTC
### UNIT3D Version

8.1.3

### PHP & Platform

8.3 Ubuntu 20

### Laravel verion

Latest in 8.1.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Show similar torrents, if no similar torrents found it should go to other page or show other than error page.

### Description

When no similar torrents found it gives error 404 

![proof4](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/74866068/1762dbc2-c660-440f-8713-f8711923222c)

Thank you all for your nice work on latest updates!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3805">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3805/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3805/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment] 2024-05-03 06:07
Pretty much a duplicate of https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/3413

Check issues before opening

**Closed** 2024-05-03 06:07 UTC
Labels: Bug, Fund
