### ISSUE TITLE
[Bug] Cannot remove existing avatar

### ISSUE THREAD

**Issue by rpatterson** [HDInnovations/UNIT3D-Community-Edition#3517] opened 2024-02-12 00:02 UTC
### UNIT3D Version

unknown

### PHP & Platform

unknown

### Laravel verion

unknown

### Have you done this?

- [ ] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

A member should be able to remove an avatar they added previously without having to replace it with a new one.

### Description

Instead, the edit form only provides a field to add a new avatar if none has been added before or *replace* the existing avatar. It doesn't offer any way to remove the existing avatar. In terms of UX, most edit actions should be reversible. A user can clear the "About Me" or "Forum Signature" fields to reverse any content previously added there, but there's no way to do the same thing for the avatar image.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by rpatterson** [comment] 2024-02-12 00:13
Arguments can be made both that this is a bug and that it is a feature request.  I could't find any contributing docs about how to submit feature requests, so I went with the only option I could find.

**Comment by HDVinnie** [comment] 2024-02-12 00:13
Duplicate of #3365

**Closed by HDVinnie** 2024-02-12 00:13 UTC
Labels: Bug

**Comment by rpatterson** [comment] 2024-02-12 02:39
> Duplicate of #3365

I found that issue when I searched for existing issues before opening a new one. I don't think this is a duplicate of #3365, @HDVinnie. This isn't about being able to *replace* an existing avatar with a new one, it's about *removing* an existing avatar and going back to no avatar.

**Comment by HDVinnie** [comment] 2024-02-12 02:49
its part of the same issue @rpatterson
