### ISSUE TITLE
[Bug] Issues loading values from config

### ISSUE THREAD

**Issue by ThyThal** [HDInnovations/UNIT3D-Community-Edition#2859] opened 2023-07-05 15:34 UTC
### UNIT3D Version

7.x.x

### PHP & Platform

8.2.7 - Ubuntu 22.04 x64

### Laravel verion

10.11.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

All the uses of config load correctly.

### Description

I don't necesarly think that this might be a bug but some miss configuration from my part but all I did was download the project and update to 7.x.x without changing anything at first.

Once I have updated the project I tried to change the other.php and it seems to not be updating anything that was changed using default values from somewere that I can't find. I did not change anything else apart from it.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by nikosuk** [comment] 2023-07-05 16:45
go to your app dir (usually /var/www/html) 

Try : php artisan cache:clear

**Comment by ThyThal** [comment] 2023-07-05 17:11
I tried that and restarted everything but nothing has changed.

**Comment by HDVinnie** [comment] 2023-07-05 17:13
> ### UNIT3D Version
> 7.x.x
> 
> ### PHP & Platform
> 8.2.7 - Ubuntu 22.04 x64
> 
> ### Laravel verion
> 10.11.0
> 
> ### Have you done this?
> * [x]  I am willing to share my stack trace and logs
> * [ ]  I can suggest a fix as a Pull Request
> 
> ### Expectation
> All the uses of config load correctly.
> 
> ### Description
> I don't necesarly think that this might be a bug but some miss configuration from my part but all I did was download the project and update to 7.x.x without changing anything at first.
> 
> Once I have updated the project I tried to change the other.php and it seems to not be updating anything that was changed using default values from somewere that I can't find. I did not change anything else apart from it.
> 
> ### Stack trace & logs
> _No response_
> 
> ### Are you a UNIT3D sponsor?
> No, don't give priority to this

For starters 7.x.x is not officially released. The `php artisan git:update` command will not bring you to 7.x.x. 7.x.x will be released once prod ready.

Regardless when you make config changes you need to run `php artisan config:clear` or what I prefer is `php artisan set:all_cache` which will recache everything. If running Opcache then obviously need to restart php as well.

The command above by @nikosuk is incorrect. That would clear the app cache aka Redis.

If answered please close this as this is not a bug and more so a Q&A for https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions

**Closed** 2023-07-05 17:23 UTC
Labels: Bug
