### ISSUE TITLE
[Bug] Errors not being reported

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1239] opened 2020-03-11 02:54 UTC
**Describe the bug**
A clear and concise description of of what the bug is.
"New install. Log files are being created with owner 'root' and consequently some Laravel errors are not being logged.
drwxrwxr-x 2 www-data www-data 4.0K Mar 11 00:03 .
drwxrwxr-x 6 www-data www-data 4.0K Mar  8 04:33 ..
-rw-rw-r-- 1 www-data www-data   16 Mar  4 16:49 .gitignore
-rw-r--r-- 1 root     root      16K Mar  4 23:00 laravel-2020-03-04.log
-rw-r--r-- 1 root     root      53K Mar  5 23:00 laravel-2020-03-05.log
-rw-r--r-- 1 root     root      53K Mar  6 23:00 laravel-2020-03-06.log
-rw-r--r-- 1 root     root      53K Mar  7 23:00 laravel-2020-03-07.log
-rw-r--r-- 1 root     root      56K Mar  8 23:00 laravel-2020-03-08.log
-rw-r--r-- 1 root     root      52K Mar  9 23:00 laravel-2020-03-09.log
-rw-r--r-- 1 root     root     209K Mar 10 23:35 laravel-2020-03-10.log
-rw-r--r-- 1 root     root      24K Mar 11 02:33 laravel-2020-03-11.log

**To Reproduce**

**Expected behavior**
All errors should be logged.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.7
- Laravel Version: 6.17.0
- PHP Version: 7.4.3
- Database Driver & Version: 5.7.29-0ubuntu0.18.04.1
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by shlandturtle** [comment] 2020-03-11 08:03
I've noticed earlier this is dependent of the error. There is a specific error that makes the file root-owned, if it's the first error for the day to be logged. The error logged might be helpful.

**Comment by cbj4074** [comment] 2020-03-11 13:56
The only way this could happen is if PHP is being executed as root. And the most likely way that could happen is if Supervisor is used and does not specify a limited-privilege user as whom to execute PHP in the Supervisor configuration.

This may also explain @shlandturtle 's observation that only certain types of errors (e.g., those caused by queued or scheduled tasks) cause this problem.

Please post your Supervisor configuration file.

**Comment by HDVinnie** [comment] 2020-03-11 14:11
`sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' +` should resolve your permissions issue.

**Comment by torman365** [comment] 2020-03-12 01:43
@cbj4074  This is the supervisor config:
# cat /etc/supervisor/conf.d/unit3d.conf 
[program:unit3d-queue]
process_name=%(programname)s%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3
startsecs = 0
autostart=true
autorestart=true
user=www-data
numprocs=2

[program:unit3d-chat-server]
process_name=%(programname)s%(process_num)02d
command=/usr/bin/node /usr/bin/laravel-echo-server start --dir=/var/www/html
autostart=true
autorestart=true
user=www-data
numprocs=1

**Comment by torman365** [comment] 2020-03-12 01:44
@HDVinnie  
We have not run any chown on the server, and these are the only files or directories under /var/www/html not owned by www-data:
# find /var/www/html -not -user www-data 
/var/www/html/storage/logs/laravel-2020-03-08.log
/var/www/html/storage/logs/laravel-2020-03-07.log
/var/www/html/storage/logs/laravel-2020-03-05.log
/var/www/html/storage/logs/laravel-2020-03-09.log
/var/www/html/storage/logs/laravel-2020-03-06.log
/var/www/html/storage/logs/laravel-2020-03-11.log
/var/www/html/storage/logs/laravel-2020-03-04.log
/var/www/html/storage/logs/laravel-2020-03-10.log
/var/www/html/laravel-echo-server.json

**Comment by HDVinnie** [comment] 2020-03-12 12:32
Run `sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' +`

**Comment by cbj4074** [comment] 2020-03-13 01:36
@HDVinnie The OP seems to be suggesting that while running those commands may "fix" the permissions, it doesn't explain how they got that way in the first place, and may not prevent the next log file that's created from having `root:root` ownership.

That said, I do think it's worth running the command once to see if indeed new log files are created with the correct ownership and permissions, or if the problem recurs. It also bears mention that @torman365 needs to `cd /path/to/laravel-app` before running that command, or that could pave-over existing permissions on the system in question (i.e., if executed in some other, arbitrary directory).

@torman365 The Supervisor config looks okay in that `user=www-data` is present.

Did you install/configure this server [automatically](https://github.com/HDInnovations/UNIT3D-Community-Edition#auto-install) or [manually](https://github.com/HDInnovations/UNIT3D-Community-Edition#manual-install) in the first place?

**Comment by torman365** [comment] 2020-03-13 03:58
We ran that command but it had no effect, Now running on new servers with modified Unit3d and XBT so will see if errors return

**Comment by torman365** [comment] 2020-03-13 04:07
@cbj4074   This is a long term problem that we have had on the previous server for months. We have checked the directory and file permissions on that, and on the new server, with no effect. We have patched the problem on the old server with a cron job that changes the log file ownership, but were hoping that the problem would be fixed with the new install on the new server.it appears not.  The install was done using the automatic install application

**Comment by cbj4074** [comment] 2020-03-13 19:02
@torman365 When you say

> We ran that command but it had no effect

what, exactly, do you mean by that? Did the command not change the ownership at all? Or the command changed ownership upon running it, but the ownership was set back to `root:root` at some later time?

**Comment by torman365** [comment] 2020-03-14 05:17
@cbj4074  It had the expected effect, in that it changed the existing files ownerships and checked their permissions,  but the next day's log file was created with root ownership as before.

**Comment by HDVinnie** [comment] 2020-03-15 00:18
So what's the last error in the log? Im guessing its a console command

**Comment by torman365** [comment] 2020-03-15 16:57
Ok, in the log today, the first error is:
"Creating default object from empty value {"exception":"[object] (ErrorException(code: 0): Creating default object from empty value at /var/www/html/app/Console/Commands/AutoHighspeedTag.php:54)"

And the most recent error is:
"Creating default object from empty value {"exception":"[object] (ErrorException(code: 0): Creating default object from empty value at /var/www/html/app/Console/Commands/AutoHighspeedTag.php:54)"
When the log is owned by root, only console command errors are loggged.

**Comment by cbj4074** [comment] 2020-03-17 23:48
@torman365 Thanks for the continued and helpful feedback.

I'm starting to wonder if there might be a cron task that is running an Artisan command as `root`.

Can you show us the content of `sudo crontab -e`?

Of course, feel free to omit anything that is irrelevant or private.

**Comment by torman365** [comment] 2020-03-18 05:46
@cbj4074 It's just the standard entry that the install created in the root crontab:
* * * * * php /var/www/html/artisan schedule:run >> /dev/null 2>&1

**Comment by cbj4074** [comment] 2020-03-19 12:28
@torman365 That's enough to cause the problem. *Nothing* relating to Laravel should be run as `root`, except Supervisor, for the obvious reason that it passes the execution flow to a different (and less privileged) user.

That crontab should be configured to run under the same user as whom PHP runs (probably `www-data`).

We'll have to look at the automated installer and see if that's where this is being configured initially, and fix it if so.

**Comment by cbj4074** [comment] 2020-03-19 14:45
The issue is here:

https://github.com/poppabear8883/UNIT3D-INSTALLER/blob/master/src/Installer/UNIT3D/Unit3dSetup.php#L155

We need to modify this to create the crontab under the same user as whom PHP runs (e.g., `www-data`). I'll take a closer look shortly.

**Comment by Golumpa** [comment] 2020-03-19 15:31
@cbj4074 If it's an issue of running the Cron as www-data, then just replace the Cron comma d to the one below and it should suffice.

`* * * * * www-data php $install_dir/artisan schedule:run >> /dev/null 2>&1\`

**Comment by innocente205** [comment] 2020-04-20 03:26
This was fixed by running the scheduler cron in /etc/crontab as the www-data user, not under the root cron as it was installed. The user was dictated by the process that instigated the first error log of the day. If it was a command it would be root, otherwise it would be the php user.

**Comment by HDVinnie** [comment] 2020-07-02 17:29
closed in https://github.com/poppabear8883/UNIT3D-INSTALLER/commit/03b00e52b4f09809c270675d4cfd7ded2596fb4a

**Closed by HDVinnie** 2020-07-02 17:29 UTC
Labels: Bug
