### ISSUE TITLE
[Bug] Duplicate bonuses if the same torrent is in 2 clients on the same machine.

### ISSUE THREAD

**Issue by espiman** [HDInnovations/UNIT3D-Community-Edition#1402] opened 2020-07-12 09:25 UTC
**Describe the bug**
The bonus system does not check the IP, therefore if I have 100 torrents in one client and I put those same 100 torrents in another client within the same pc, 200 torrents appear in the bonds.

**To Reproduce**
1. Duplicate same torrent in another cliente on the same machine
2. Go to BON Points view and check that duplicate bonuses apply.

**Expected behavior**
In all the queries of the peers of each bond, check for a distinct ip.

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.5.0
- Laravel Version: 6.18.18
- PHP Version: 7.4.7
- Database Driver & Version: 5.7.30
- Web Server Driver & Version: nginx 1.15.8
- OS Driver and Version: 18.04.1

**Desktop (please complete the following information):**
 - OS: Windows / MAC
 - Browser: Chrome / Firefox
 - Version:

**Comment by HDVinnie** [comment] 2020-07-12 12:31
Duplicate of https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1390

**Closed by HDVinnie** 2020-07-12 12:31 UTC
Labels: Bug
