### ISSUE TITLE
Ability to change the BON store criteria from the staff dashboard[Feature]

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D-Community-Edition#1044] opened 2019-12-30 13:54 UTC
As the title suggests, it would be nice to change the criteria for the BON Store from the staff panel.

So you could change how old a torrent must be to be an old torrent, how many points a user will get, what the file size needs to be and how many points the users should be getting.

**Comment by xR4E** [comment] 2019-12-30 13:59
I just found a similar request here: https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/360

It's a similar request, maybe you'll merge them!

**Comment by HDVinnie** [comment] 2019-12-30 16:19
Duplicate of #360

**Closed by HDVinnie** 2019-12-30 16:19 UTC
Labels: Duplicate
