### ISSUE TITLE
[Bug] Illegal port 1 - SOCKS5 Proxy

### ISSUE THREAD

**Issue by tfurmanator** [HDInnovations/UNIT3D-Community-Edition#3847] opened 2024-05-22 02:34 UTC
### UNIT3D Version

.

### PHP & Platform

.

### Laravel verion

.

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

I should be able to connect to UNIT3D trackers using a SOCKS5 proxy. Any other private trackers allow this proxy protocol.

### Description

When I connect to any UNIT3D based tracker, I get this error:

```
Illegal port 1 . Port should be between 6881-64999
```

I have changed my SOCKS5 proxy listening port from 53 (default) to different ports within the specified range. I believe this port is internal and unrelated.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3847">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3847/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3847/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment] 2024-05-22 02:46
This is a duplicate of https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/3428

Please read it in full.

**Closed by HDVinnie** 2024-05-22 02:46 UTC
Labels: Bug, Fund

**Comment by tfurmanator** [comment] 2024-05-22 02:53
Yeah I see that, but I'm still not able to use UNIT3D trackers because this issue still exists

**Comment by Roardom** [comment] 2024-05-22 03:01
Use a client that doesn't fake its listening port. There is no plan to change the logic.

**Comment by tfurmanator** [comment] 2024-05-22 03:07
I'm using qBittorrent and a SOCKS5 VPN proxy.

Why does only UNIT3D block this and not any other trackers? I'm able to seed and leech elsewhere just fine.

I understand you need to implement security rules but this is blocking legitimate users.

**Comment by HDVinnie** [comment] 2024-05-22 03:16
> I'm using qBittorrent and a SOCKS5 VPN proxy.
> 
> Why does only UNIT3D block this and not any other trackers? I'm able to seed and leech elsewhere just fine.
> 
> I understand you need to implement security rules but this is blocking legitimate users.

The logic in UNIT3D is 100% correct. No client should be using a port below 1024. You say the issue still exists but its not an issue with UNIT3D. Its your client or client settings. Make sure UPNP is disabled. Open an issue with Qbittorrent. If you changed to port to above 1024 and still getting error then the port didn't actually change.

**Comment by tfurmanator** [comment] 2024-05-22 03:37
I see, thanks for the clarification. Sorry for misunderstanding. I will try with other clients or open an issue with qbit.
