### ISSUE TITLE
[Bug] - After Upload torrent - Error

### ISSUE THREAD

**Issue by TheFelin** [HDInnovations/UNIT3D-Community-Edition#1509] opened 2020-12-11 15:42 UTC
After uploading the torrent file the server returns an error. The file is indeed sent.
I can't find an error message
there are other users with the same problem.

**Comment by nikosuk** [comment] 2020-12-11 15:44
check your staff panel , Laravel Logs 
What you say here , gives no info

**Comment by TheFelin** [comment] 2020-12-11 16:07
Nothing....

**Comment by TheFelin** [comment] 2020-12-11 16:21
fwrite(): send of 15 bytes failed with errno=32 Broken pipe {"userId":3,"exception":"[object] (ErrorException(code: 0): fwrite(): send of 15 bytes failed with errno=32 Broken pipe at /var/www/html/app/Bots/IRCAnnounceBot.php:94)

**Comment by nikosuk** [comment] 2020-12-11 16:31
go to /var/www/html/config
edit and disable irc bot

**Comment by TheFelin** [comment] 2020-12-11 16:46
Address in mailbox given [TheFelin] does not comply with RFC 2822, 3.6.2. {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [TheFelin] does not comply with RFC 2822, 3.6.2. at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)

**Comment by HDVinnie** [comment] 2020-12-11 18:56
Dupe of #1490 and next time follow the issue template in full!

**Closed by HDVinnie** 2020-12-11 18:56 UTC
Labels: Bug
