### ISSUE TITLE
[Bug] Multiple quotes in one forum post get joined together

### ISSUE THREAD

**Issue by shlandturtle** [HDInnovations/UNIT3D-Community-Edition#1243] opened 2020-03-13 17:21 UTC
Describe the bug
All quotes done using the quote button on the forum causes all content since the first until the last quote to be joined into one big quote.

To Reproduce
Quote someones post, add text after it and post it.
Quote it again to make another post, first quote and it's post are joined into one quote when posting. The quote of first post is essentially just inside the post you are quoting, saying it's a quote.

-OR-
Quote two posts in your reply
Add text in between
After posting the two quotes as well as the text in between will be one big quote.

UNIT3D (please complete the following information):

    UNIT3D Version: 2.2.7
    Laravel Version: 6.17.0
    PHP Version: 7.4.2
    Database Driver & Version: mysql 5.7.29
    Web Server Driver & Version: nginx 1.15.8
    OS Driver and Version: Ubuntu 18.04

Possible Fix?
HTML `<blockquote>` tag works as intended, so the quote functionality could be changed to use that instead, and the quote button in the editor from `[quote]` to `<blockquote>`.
However, this hides who you are quoting, it needs to specifically be written to the text.

**Comment by HDVinnie** [comment] 2020-12-08 22:14
duplicate of https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1448

**Closed by HDVinnie** 2020-12-08 22:14 UTC
